name: blog @ mandrewcito
markdown: kramdown
highlighter: rouge
exclude: ["LICENSE.txt", "README.md", "Makefile", "Gemfile", "Gemfile.lock"]
site.title: blog @ mandrewcito

baseurl: ""
permalink: /:title/

repository:  mandrewcito/blog.mandrewcito.com
author: Andrés Baamonde Lozano

# Paginate
paginate: 1
paginate_path: "/pagination/page:num/"


# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache
  - jekyll-remote-theme
  
# jekyll-multiple-languages-plugin settings:
languages: ["gl", "en", "es"]

exclude_from_localizations: ["javascript", "images", "css", "scripts", "favicon.ico"]