name: blog.mandrewcito.com
markdown: kramdown
highlighter: pygments
exclude: ["LICENSE.txt", "README.md", "Makefile"]
site:
  name: blog.mandrewcito.com

baseurl: ""
permalink: /:title/


# Paginate
paginate: 1
paginate_path: "/pagination/page:num/"


# Plugins
plugins:
  - jekyll-multiple-languages-plugin
  - jekyll-paginate


# jekyll-multiple-languages-plugin settings:
languages: ["gl", "en", "es"]

exclude_from_localizations: ["javascript", "images", "css", "scripts", "favicon.ico"]

theme: jekyll-theme-minimal